name: elmfire_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - mpi4py
  - google-api-python-client
  - grpcio
  - grpcio-tools
  - python-dateutil
  - numpy
  - pandas
  - geopandas
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - gdal
